#############################################################################
# Makefile for building: SudokuScalian.app/Contents/MacOS/SudokuScalian
# Generated by qmake (3.1) (Qt 6.5.3)
# Project:  SudokuScalian.pro
# Template: app
# Command: /Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/bin/qmake -o Makefile SudokuScalian.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers -I../Qt/6.5.3/macos/lib/QtGui.framework/Headers -I../Qt/6.5.3/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/AGL.framework/Headers -I../Qt/6.5.3/macos/mkspecs/macx-clang -F/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/lib
QMAKE         = /Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SudokuScalian1.0.0
DISTDIR = /Users/alejandrohidalgopaniagua/SudokuScalian/.tmp/SudokuScalian1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/lib
LIBS          = $(SUBLIBS) -F/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		scaliansudoku.cpp qrc_resources.cpp \
		qrc_qmake_qmake_qm_files.cpp \
		moc_scaliansudoku.cpp
OBJECTS       = main.o \
		scaliansudoku.o \
		qrc_resources.o \
		qrc_qmake_qmake_qm_files.o \
		moc_scaliansudoku.o
DIST          = ../Qt/6.5.3/macos/mkspecs/features/spec_pre.prf \
		../Qt/6.5.3/macos/mkspecs/features/device_config.prf \
		../Qt/6.5.3/macos/mkspecs/common/unix.conf \
		../Qt/6.5.3/macos/mkspecs/common/mac.conf \
		../Qt/6.5.3/macos/mkspecs/common/macx.conf \
		../Qt/6.5.3/macos/mkspecs/common/sanitize.conf \
		../Qt/6.5.3/macos/mkspecs/common/gcc-base.conf \
		../Qt/6.5.3/macos/mkspecs/common/gcc-base-mac.conf \
		../Qt/6.5.3/macos/mkspecs/common/clang.conf \
		../Qt/6.5.3/macos/mkspecs/common/clang-mac.conf \
		../Qt/6.5.3/macos/mkspecs/qconfig.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_ext_archive.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_ext_freetype.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_ext_libpng.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_ext_taglib.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_ext_yaml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_application_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_common_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_crypto_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_dbus_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_intent_client_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_intent_server_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_launcher_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_main_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_manager_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_monitor_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_notification_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_package_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_plugininterfaces_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_shared_main_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_window_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_charts.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_coap.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_coap_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_core.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_declarativeopcua.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_designer.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_grpc.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_grpc_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_gui.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_help.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_httpserver.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_httpserver_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifmedia.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifmedia_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifremoteobjects_helper_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifvehiclefunctions.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifvehiclefunctions_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_insighttracker.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_insighttracker_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_interfaceframework.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_interfaceframework_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_linguist.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_location.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_mqtt.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_mqtt_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_network.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_opcua.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_opcua_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdf.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_png_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_protobuf.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_protobuf_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcompilerplus_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sql.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_statemachine.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_svg.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_vncserver.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_vncserver_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_vncserverquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webview.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_xml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../Qt/6.5.3/macos/mkspecs/features/qt_functions.prf \
		../Qt/6.5.3/macos/mkspecs/features/qt_config.prf \
		../Qt/6.5.3/macos/mkspecs/macx-clang/qmake.conf \
		../Qt/6.5.3/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/6.5.3/macos/mkspecs/features/exclusive_builds.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/sdk.prf \
		../Qt/6.5.3/macos/mkspecs/features/toolchain.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/toolchain.prf \
		../Qt/6.5.3/macos/mkspecs/features/default_pre.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/default_pre.prf \
		../Qt/6.5.3/macos/mkspecs/features/resolve_config.prf \
		../Qt/6.5.3/macos/mkspecs/features/default_post.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/default_post.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/objective_c.prf \
		../Qt/6.5.3/macos/mkspecs/features/lrelease.prf \
		../Qt/6.5.3/macos/mkspecs/features/qml_debug.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/mac.prf \
		../Qt/6.5.3/macos/mkspecs/features/warn_on.prf \
		../Qt/6.5.3/macos/mkspecs/features/permissions.prf \
		../Qt/6.5.3/macos/mkspecs/features/qt.prf \
		../Qt/6.5.3/macos/mkspecs/features/resources_functions.prf \
		../Qt/6.5.3/macos/mkspecs/features/resources.prf \
		../Qt/6.5.3/macos/mkspecs/features/moc.prf \
		../Qt/6.5.3/macos/mkspecs/features/unix/opengl.prf \
		../Qt/6.5.3/macos/mkspecs/features/uic.prf \
		../Qt/6.5.3/macos/mkspecs/features/unix/thread.prf \
		../Qt/6.5.3/macos/mkspecs/features/qmake_use.prf \
		../Qt/6.5.3/macos/mkspecs/features/file_copies.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/rez.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/6.5.3/macos/mkspecs/features/testcase_targets.prf \
		../Qt/6.5.3/macos/mkspecs/features/exceptions.prf \
		../Qt/6.5.3/macos/mkspecs/features/yacc.prf \
		../Qt/6.5.3/macos/mkspecs/features/lex.prf \
		SudokuScalian.pro scaliansudoku.h main.cpp \
		scaliansudoku.cpp
QMAKE_TARGET  = SudokuScalian
DESTDIR       = 
TARGET        = SudokuScalian.app/Contents/MacOS/SudokuScalian

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 14.0
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/alejandrohidalgopaniagua/SudokuScalian/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/alejandrohidalgopaniagua/SudokuScalian/SudokuScalian.pro


include /Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

SudokuScalian.app/Contents/MacOS/SudokuScalian: ui_scaliansudoku.h $(OBJECTS)  
	@test -d SudokuScalian.app/Contents/MacOS/ || mkdir -p SudokuScalian.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SudokuScalian.pro ../Qt/6.5.3/macos/mkspecs/macx-clang/qmake.conf ../Qt/6.5.3/macos/mkspecs/features/spec_pre.prf \
		../Qt/6.5.3/macos/mkspecs/features/device_config.prf \
		../Qt/6.5.3/macos/mkspecs/common/unix.conf \
		../Qt/6.5.3/macos/mkspecs/common/mac.conf \
		../Qt/6.5.3/macos/mkspecs/common/macx.conf \
		../Qt/6.5.3/macos/mkspecs/common/sanitize.conf \
		../Qt/6.5.3/macos/mkspecs/common/gcc-base.conf \
		../Qt/6.5.3/macos/mkspecs/common/gcc-base-mac.conf \
		../Qt/6.5.3/macos/mkspecs/common/clang.conf \
		../Qt/6.5.3/macos/mkspecs/common/clang-mac.conf \
		../Qt/6.5.3/macos/mkspecs/qconfig.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_ext_archive.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_ext_freetype.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_ext_libpng.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_ext_taglib.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_ext_yaml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_application_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_common_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_crypto_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_dbus_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_intent_client_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_intent_server_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_launcher_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_main_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_manager_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_monitor_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_notification_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_package_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_plugininterfaces_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_shared_main_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_window_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_charts.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_coap.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_coap_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_core.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_declarativeopcua.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_designer.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_grpc.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_grpc_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_gui.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_help.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_httpserver.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_httpserver_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifmedia.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifmedia_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifremoteobjects_helper_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifvehiclefunctions.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifvehiclefunctions_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_insighttracker.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_insighttracker_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_interfaceframework.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_interfaceframework_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_linguist.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_location.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_mqtt.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_mqtt_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_network.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_opcua.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_opcua_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdf.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_png_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_protobuf.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_protobuf_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcompilerplus_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sql.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_statemachine.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_svg.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_vncserver.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_vncserver_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_vncserverquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webview.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_xml.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../Qt/6.5.3/macos/mkspecs/features/qt_functions.prf \
		../Qt/6.5.3/macos/mkspecs/features/qt_config.prf \
		../Qt/6.5.3/macos/mkspecs/macx-clang/qmake.conf \
		../Qt/6.5.3/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/6.5.3/macos/mkspecs/features/exclusive_builds.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/sdk.prf \
		../Qt/6.5.3/macos/mkspecs/features/toolchain.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/toolchain.prf \
		../Qt/6.5.3/macos/mkspecs/features/default_pre.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/default_pre.prf \
		../Qt/6.5.3/macos/mkspecs/features/resolve_config.prf \
		../Qt/6.5.3/macos/mkspecs/features/default_post.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/default_post.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/objective_c.prf \
		../Qt/6.5.3/macos/mkspecs/features/lrelease.prf \
		../Qt/6.5.3/macos/mkspecs/features/qml_debug.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/mac.prf \
		../Qt/6.5.3/macos/mkspecs/features/warn_on.prf \
		../Qt/6.5.3/macos/mkspecs/features/permissions.prf \
		../Qt/6.5.3/macos/mkspecs/features/qt.prf \
		../Qt/6.5.3/macos/mkspecs/features/resources_functions.prf \
		../Qt/6.5.3/macos/mkspecs/features/resources.prf \
		../Qt/6.5.3/macos/mkspecs/features/moc.prf \
		../Qt/6.5.3/macos/mkspecs/features/unix/opengl.prf \
		../Qt/6.5.3/macos/mkspecs/features/uic.prf \
		../Qt/6.5.3/macos/mkspecs/features/unix/thread.prf \
		../Qt/6.5.3/macos/mkspecs/features/qmake_use.prf \
		../Qt/6.5.3/macos/mkspecs/features/file_copies.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/rez.prf \
		../Qt/6.5.3/macos/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/6.5.3/macos/mkspecs/features/testcase_targets.prf \
		../Qt/6.5.3/macos/mkspecs/features/exceptions.prf \
		../Qt/6.5.3/macos/mkspecs/features/yacc.prf \
		../Qt/6.5.3/macos/mkspecs/features/lex.prf \
		SudokuScalian.pro \
		Resources/resources.qrc \
		qmake_qmake_qm_files.qrc \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../Qt/6.5.3/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../Qt/6.5.3/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile SudokuScalian.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../Qt/6.5.3/macos/mkspecs/features/spec_pre.prf:
../Qt/6.5.3/macos/mkspecs/features/device_config.prf:
../Qt/6.5.3/macos/mkspecs/common/unix.conf:
../Qt/6.5.3/macos/mkspecs/common/mac.conf:
../Qt/6.5.3/macos/mkspecs/common/macx.conf:
../Qt/6.5.3/macos/mkspecs/common/sanitize.conf:
../Qt/6.5.3/macos/mkspecs/common/gcc-base.conf:
../Qt/6.5.3/macos/mkspecs/common/gcc-base-mac.conf:
../Qt/6.5.3/macos/mkspecs/common/clang.conf:
../Qt/6.5.3/macos/mkspecs/common/clang-mac.conf:
../Qt/6.5.3/macos/mkspecs/qconfig.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_ext_archive.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_ext_freetype.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_ext_libpng.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_ext_taglib.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_ext_yaml.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3danimation.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3danimation_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dextras.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickanimation.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3drender.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_application_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_common_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_crypto_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_dbus_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_intent_client_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_intent_server_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_launcher_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_main_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_manager_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_monitor_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_notification_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_package_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_plugininterfaces_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_shared_main_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_appman_window_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_bodymovin_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_charts.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_charts_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_chartsqml.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_coap.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_coap_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_core.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_core5compat.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_core5compat_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_core_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_datavisualization.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_datavisualization_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_dbus.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_declarativeopcua.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_designer.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_grpc.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_grpc_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_gui.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_help.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_help_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_httpserver.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_httpserver_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifmedia.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifmedia_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifremoteobjects_helper_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifvehiclefunctions.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_ifvehiclefunctions_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_insighttracker.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_insighttracker_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_insighttrackerqml.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_insighttrackerqml_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_interfaceframework.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_interfaceframework_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssettings.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_languageserver_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_linguist.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_location.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_location_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_mqtt.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_mqtt_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_network.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_network_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_networkauth.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_networkauth_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_nfc.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_opcua.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_opcua_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_opengl.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdf.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdf_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdfquick.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdfquick_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdfwidgets.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_png_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_positioning.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_positioningquick.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_positioningquick_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_protobuf.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_protobuf_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qml.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcompilerplus_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3d.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dphysics.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_remoteobjects.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_repparser.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_repparser_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_scxml.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_scxmlqml.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sensors.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sensorsquick.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_serialbus.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_serialport.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_shadertools.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sql.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_statemachine.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_statemachine_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_statemachineqml.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_svg.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_testlib.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_tools_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_uitools.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_vncserver.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_vncserver_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_vncserverquick_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginecore.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginequick.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginequick_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_websockets.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webview.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webview_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webviewquick.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_webviewquick_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_widgets.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_xml.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../Qt/6.5.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../Qt/6.5.3/macos/mkspecs/features/qt_functions.prf:
../Qt/6.5.3/macos/mkspecs/features/qt_config.prf:
../Qt/6.5.3/macos/mkspecs/macx-clang/qmake.conf:
../Qt/6.5.3/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/6.5.3/macos/mkspecs/features/exclusive_builds.prf:
../Qt/6.5.3/macos/mkspecs/features/mac/sdk.prf:
../Qt/6.5.3/macos/mkspecs/features/toolchain.prf:
../Qt/6.5.3/macos/mkspecs/features/mac/toolchain.prf:
../Qt/6.5.3/macos/mkspecs/features/default_pre.prf:
../Qt/6.5.3/macos/mkspecs/features/mac/default_pre.prf:
../Qt/6.5.3/macos/mkspecs/features/resolve_config.prf:
../Qt/6.5.3/macos/mkspecs/features/default_post.prf:
../Qt/6.5.3/macos/mkspecs/features/mac/default_post.prf:
../Qt/6.5.3/macos/mkspecs/features/mac/objective_c.prf:
../Qt/6.5.3/macos/mkspecs/features/lrelease.prf:
../Qt/6.5.3/macos/mkspecs/features/qml_debug.prf:
../Qt/6.5.3/macos/mkspecs/features/mac/mac.prf:
../Qt/6.5.3/macos/mkspecs/features/warn_on.prf:
../Qt/6.5.3/macos/mkspecs/features/permissions.prf:
../Qt/6.5.3/macos/mkspecs/features/qt.prf:
../Qt/6.5.3/macos/mkspecs/features/resources_functions.prf:
../Qt/6.5.3/macos/mkspecs/features/resources.prf:
../Qt/6.5.3/macos/mkspecs/features/moc.prf:
../Qt/6.5.3/macos/mkspecs/features/unix/opengl.prf:
../Qt/6.5.3/macos/mkspecs/features/uic.prf:
../Qt/6.5.3/macos/mkspecs/features/unix/thread.prf:
../Qt/6.5.3/macos/mkspecs/features/qmake_use.prf:
../Qt/6.5.3/macos/mkspecs/features/file_copies.prf:
../Qt/6.5.3/macos/mkspecs/features/mac/rez.prf:
../Qt/6.5.3/macos/mkspecs/features/mac/asset_catalogs.prf:
../Qt/6.5.3/macos/mkspecs/features/testcase_targets.prf:
../Qt/6.5.3/macos/mkspecs/features/exceptions.prf:
../Qt/6.5.3/macos/mkspecs/features/yacc.prf:
../Qt/6.5.3/macos/mkspecs/features/lex.prf:
SudokuScalian.pro:
Resources/resources.qrc:
qmake_qmake_qm_files.qrc:
../Qt/6.5.3/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../Qt/6.5.3/macos/lib/QtGui.framework/Resources/QtGui.prl:
../Qt/6.5.3/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SudokuScalian.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

SudokuScalian.app/Contents/PkgInfo: 
	@test -d SudokuScalian.app/Contents || mkdir -p SudokuScalian.app/Contents
	@$(DEL_FILE) SudokuScalian.app/Contents/PkgInfo
	@echo "APPL????" > SudokuScalian.app/Contents/PkgInfo
SudokuScalian.app/Contents/Info.plist: 
	@test -d SudokuScalian.app/Contents || mkdir -p SudokuScalian.app/Contents
	@$(DEL_FILE) SudokuScalian.app/Contents/Info.plist
	@plutil -convert xml1 -o - ../Qt/6.5.3/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.SudokuScalian,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.SudokuScalian,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,SudokuScalian,g" -e "s,@LIBRARY@,SudokuScalian,g" -e "s,\$${EXECUTABLE_NAME},SudokuScalian,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >SudokuScalian.app/Contents/Info.plist

all: Makefile \
		SudokuScalian.app/Contents/PkgInfo \
		SudokuScalian.app/Contents/Info.plist SudokuScalian.app/Contents/MacOS/SudokuScalian

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents SudokuScalian_es_ES.ts $(DISTDIR)/
	$(COPY_FILE) --parents Resources/resources.qrc qmake_qmake_qm_files.qrc $(DISTDIR)/
	$(COPY_FILE) --parents scaliansudoku.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp scaliansudoku.cpp $(DISTDIR)/
	$(COPY_FILE) --parents scaliansudoku.ui $(DISTDIR)/
	$(COPY_FILE) --parents SudokuScalian_es_ES.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r SudokuScalian.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_lrelease_make_all: .qm/SudokuScalian_es_ES.qm
compiler_lrelease_clean:
	-$(DEL_FILE) .qm/SudokuScalian_es_ES.qm
.qm/SudokuScalian_es_ES.qm: SudokuScalian_es_ES.ts
	/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/bin/lrelease SudokuScalian_es_ES.ts -qm .qm/SudokuScalian_es_ES.qm

compiler_rcc_make_all: qrc_resources.cpp qrc_qmake_qmake_qm_files.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp qrc_qmake_qmake_qm_files.cpp
qrc_resources.cpp: Resources/resources.qrc \
		../Qt/6.5.3/macos/libexec/rcc \
		Resources/LogoScalian.png \
		Resources/Campus42Logo.png
	/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/libexec/rcc -name resources --no-zstd Resources/resources.qrc -o qrc_resources.cpp

qrc_qmake_qmake_qm_files.cpp: qmake_qmake_qm_files.qrc \
		../Qt/6.5.3/macos/libexec/rcc \
		.qm/SudokuScalian_es_ES.qm
	/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/libexec/rcc -name qmake_qmake_qm_files --no-zstd qmake_qmake_qm_files.qrc -o qrc_qmake_qmake_qm_files.cpp

compiler_moc_header_make_all: moc_scaliansudoku.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_scaliansudoku.cpp
moc_scaliansudoku.cpp: scaliansudoku.h \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/QLabel \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../Qt/6.5.3/macos/lib/QtGui.framework/Headers/QColor \
		../Qt/6.5.3/macos/lib/QtGui.framework/Headers/qcolor.h \
		../Qt/6.5.3/macos/libexec/moc
	/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=15 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/mkspecs/macx-clang -I/Users/alejandrohidalgopaniagua/SudokuScalian -I/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/lib/QtWidgets.framework/Headers -I/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/lib/QtGui.framework/Headers -I/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/lib scaliansudoku.h -o moc_scaliansudoku.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_scaliansudoku.h
compiler_uic_clean:
	-$(DEL_FILE) ui_scaliansudoku.h
ui_scaliansudoku.h: scaliansudoku.ui \
		../Qt/6.5.3/macos/libexec/uic
	/Users/alejandrohidalgopaniagua/Qt/6.5.3/macos/libexec/uic scaliansudoku.ui -o ui_scaliansudoku.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_lrelease_clean compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp scaliansudoku.h \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/QLabel \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../Qt/6.5.3/macos/lib/QtGui.framework/Headers/QColor \
		../Qt/6.5.3/macos/lib/QtGui.framework/Headers/qcolor.h \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/QApplication \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/qapplication.h \
		../Qt/6.5.3/macos/lib/QtCore.framework/Headers/QLocale \
		../Qt/6.5.3/macos/lib/QtCore.framework/Headers/qlocale.h \
		../Qt/6.5.3/macos/lib/QtCore.framework/Headers/QTranslator \
		../Qt/6.5.3/macos/lib/QtCore.framework/Headers/qtranslator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

scaliansudoku.o: scaliansudoku.cpp scaliansudoku.h \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/QLabel \
		../Qt/6.5.3/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../Qt/6.5.3/macos/lib/QtGui.framework/Headers/QColor \
		../Qt/6.5.3/macos/lib/QtGui.framework/Headers/qcolor.h \
		ui_scaliansudoku.h \
		../Qt/6.5.3/macos/lib/QtGui.framework/Headers/QPixmap \
		../Qt/6.5.3/macos/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scaliansudoku.o scaliansudoku.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

qrc_qmake_qmake_qm_files.o: qrc_qmake_qmake_qm_files.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qmake_qmake_qm_files.o qrc_qmake_qmake_qm_files.cpp

moc_scaliansudoku.o: moc_scaliansudoku.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scaliansudoku.o moc_scaliansudoku.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/SudokuScalian/bin || mkdir -p $(INSTALL_ROOT)/opt/SudokuScalian/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/SudokuScalian/bin/SudokuScalian.app
	
	$(QINSTALL) SudokuScalian.app $(INSTALL_ROOT)/opt/SudokuScalian/bin/SudokuScalian.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/SudokuScalian/bin/SudokuScalian.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/SudokuScalian/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

